msmtp_package: msmtp
msmtp_auth: "on"
msmtp_tls: "on"
msmtp_tls_starttls: "on"
msmtp_set_from_header: "on"
msmtp_domain: "{{ mail_hostname }}"
msmtp_port: 587

# msmtp_accounts:
#   - name: account_name
#     host: smtp.example.com
#     port: 587                          # optional, defaults to msmtp_port
#     from: user@example.com
#     user: user@example.com
#     password: "{{ vault_smtp_password }}"
#     auth: "on"                         # optional, defaults to msmtp_auth
#     tls: "on"                          # optional, defaults to msmtp_tls
#     tls_starttls: "on"                 # optional, defaults to msmtp_tls_starttls
#     domain: example.com                # optional, defaults to msmtp_domain
msmtp_accounts: []
