---
roles:
  - name: composer
    src: geerlingguy.composer
    version: 1.9.2

  - name: ntp
    src: geerlingguy.ntp
    version: 2.5.0

  - name: logrotate
    src: nickhammond.logrotate
    version: v0.0.5

  - name: swapfile
    src: oefenweb.swapfile
    version: v2.0.38

  - name: mailpit
    src: roots.mailpit
    version: v1.0.0
