- name: composer
  src: geerlingguy.composer
  version: 1.5.0

- name: ntp
  src: resmo.ntp
  version: 0.3.0

- name: logrotate
  src: nickhammond.logrotate
  version: e7a498d

- name: swapfile
  src: kamaln7.swapfile
  version: 0.4

- src: geerlingguy.daemonize
  version: 1.1.0

- name: mailhog
  src: geerlingguy.mailhog
  version: 1.0.5

- name: ansible
  src: geerlingguy.ansible
  version: 1.0.4

- name: newrelic-servers
  src: primozcigler.newrelic-servers
  version: v1.0.0
