---
- name: Fetch data from prod server and overwrite local WP installations
  hosts: as
  sudo: yes
  roles:
    - { role: sandbox-remote, tags: [sandbox-remote] }

- name: Perform local actions on sandbox server
  hosts: sbs
  sudo: yes
  roles:
    - { role: sandbox-local, tags: [sandbox-local] }

- name: Deploy XML files
  hosts: as
  become: yes
  become_user: deployer
  tasks:
    - name: Ensure target dir exists
      file:
        state: directory
        path: "{{ xml_paths.remote }}/"

    - name: Deploy latest XML files to as
      copy:
        src:  "{{ xml_paths.local }}/{{ item }}.wordpress.{{ ansible_date_time.date }}.000.xml"
        dest: "{{ xml_paths.remote }}/"
      with_items: "{{ sites_to_export }}"

    - name: Symlink to these latest files
      file:
        state: link
        src:   "{{ xml_paths.remote }}/{{ item }}.wordpress.{{ ansible_date_time.date }}.000.xml"
        dest:  "{{ xml_paths.remote }}/{{ item }}-latest.xml"
      with_items: sites_to_export

    - name: Clean old XMLs # backslashes should be double escaped
      command: "find . -regextype posix-egrep -regex '^\\.\\/({{ sites_to_export | join( '|' ) }})\\..+\\.xml$' -mtime +5 -exec rm {} +"
      args:
        chdir: "{{ xml_paths.remote }}/"
