---
- name: Fetch data from prod server and overwrite local WP installations
  hosts: sandbox:&production_over_private # intersection of groups sandbox and production_over_private - connect to production server via private network
  become: yes
  remote_user: "{{ admin_user }}"
  roles:
    - { role: sandbox-remote, tags: [sandbox-remote] }

- name: Perform local actions on sandbox server
  hosts: local:&sandbox  # intersection of groups local and sandbox - perform local actions
  connection: local
  become: yes
  roles:
    - { role: wordpress-mail-toggle, wordpress_disable_emails: true, tags: [wordpress-mail-toggle] }
    - { role: sandbox-local, tags: [sandbox-local] }
    - { role: wordpress-mail-toggle, wordpress_disable_emails: false, tags: [wordpress-mail-toggle] }

- name: Deploy XML files
  hosts: sandbox:&production_over_private
  become: yes
  become_user: "{{ web_user }}"
  when: false # TODO remove
  tasks:
    - name: Ensure target dir exists
      file:
        state: directory
        path: "{{ sandbox_config.xml_paths.remote }}/"

    - name: "Deploy latest XML files to {{ ansible_hostname }}"
      copy:
        src: "{{ sandbox_config.xml_paths.local }}/{{ item }}.wordpress.{{ ansible_date_time.date }}.000.xml"
        dest: "{{ sandbox_config.xml_paths.remote }}/"
      with_items: "{{ sites_to_export }}"

    - name: Symlink to these latest files
      file:
        state: link
        src: "{{ sandbox_config.xml_paths.remote }}/{{ item }}.wordpress.{{ ansible_date_time.date }}.000.xml"
        dest: "{{ sandbox_config.xml_paths.remote }}/{{ item }}-latest.xml"
      with_items: "{{ sites_to_export }}"

    - name: Clean old XMLs # backslashes should be double escaped
      command: "find . -regextype posix-egrep -regex '^\\./({{ sites_to_export | join( '|' ) }})\\..+\\.xml$' -mtime +5 -exec rm -f {} +"
      args:
        chdir: "{{ sandbox_config.xml_paths.remote }}/"
