# enable 0-RTT (rtt0)
ssl_early_data on;
proxy_set_header Early-Data $ssl_early_data;

# HTTP/3 Early-Data/0-RTT replay attack mitigation for non-GET requests
if ($reject_early_data) {
    return 425;
}
