# 0-RTT (rtt0) is TLS 1.3-specific.
# Can improve performance for returning visitors, as in the HTTP protocols.
ssl_early_data on;
proxy_set_header Early-Data $ssl_early_data;

# Mitigate early-Data/0-RTT replay attacks
# Only idempotent GET/HEAD methods are safe.
# Reject non-safe (POST/PUT) methods with 425 to force safe 1-RTT retry.
if ($reject_early_data) {
    return 425;
}
