---
- name: Install msmtp
  apt:
    name:
      - "{{ msmtp_package }}"
      - msmtp-mta
    state: "{{ msmtp_package_state | default(apt_package_state) }}"
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Remove ssmtp
  apt:
    name: ssmtp
    state: absent
    purge: true

- name: Remove ssmtp configuration directory
  file:
    path: /etc/ssmtp
    state: absent

- name: msmtp configuration
  template:
    src: msmtprc.j2
    dest: /etc/msmtprc
    mode: '0600'
