---
- name: "Setup composer authentications (HTTP Basic) - {{ site }}"
  composer:
    command: config
    arguments: --auth http-basic.{{ item.hostname | quote }} {{ item.username | quote }} {{ item.password | default("") | quote }}
    working_dir: "{{ working_dir }}"
  become: no
  no_log: true
  changed_when: false
  when:
    - item.hostname is defined and item.hostname != ""
    - item.username is defined and item.username != ""
  loop: "{{ composer_authentications_using_basic_auth }}"
  loop_control:
    label: "{{ item.type | default('default-type') }}.{{ item.hostname }}"

- name: "Setup composer authentications (BitBucket OAuth) - {{ site }}"
  composer:
    command: config
    arguments: --auth bitbucket-oauth.{{ item.hostname | quote }} {{ item.consumer_key | quote }} {{ item.consumer_secret | quote }}
    working_dir: "{{ working_dir }}"
  become: no
  no_log: true
  changed_when: false
  when:
    - item.hostname is defined and item.hostname != ""
    - item.consumer_key is defined and item.consumer_key != ""
    - item.consumer_secret is defined and item.consumer_secret != ""
  loop: "{{ composer_authentications_using_bitbucket_oauth }}"
  loop_control:
    label: "{{ item.type }}.{{ item.hostname }}"

- name: "Setup composer authentications (Other Tokens) - {{ site }}"
  composer:
    command: config
    arguments: --auth {{ item.type | quote }}.{{ item.hostname | quote }} {{ item.token | quote }}
    working_dir: "{{ working_dir }}"
  become: no
  no_log: true
  changed_when: false
  when:
    - item.hostname is defined and item.hostname != ""
    - item.token is defined and item.token != ""
  loop: "{{ composer_authentications_using_other_token }}"
  loop_control:
    label: "{{ item.type }}.{{ item.hostname }}"
